```{r}
library(readr)
library(readxl)
library(dplyr)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(Metrics)
library(gtrendsR)
library(tsbox)
library(zoo)
library(tseries)
library(tempdisagg)
library(x12)
library(trendecon)
library(gtrendsR)

```

## GET DATA & SAVE IT FOR F&D CATEGORY (all subcat data)

```{r}
#### PCA mit allen categories für eine Main category - wie Paper Heik:
geo = "AT"
data('categories') 

cat_FD <- c(71,277,404, 406, 405, 906, 122, 907, 908, 909, 910, 825, 911,912, 913,914,915, 297, 121,560, 916, 276, 917, 918, 816) # enter all e.g Food subcategoriesy  <- NULL


cat_Educ <- c(74, 1289, 1015, 1195, 799, 372, 367, 1012, 1266, 254, 791,792, 1087, 371, 1118, 373, 1308, 700, 1388, 369, 1299, 60, 959, 802, 960, 961)

#1) geht data (unsampled)

y  <- NULL

for (i in cat_FD) {
  
  data_FD <- gtrends(
    category = i,
    geo     = "AT",
    time = "all")
  
  data_FD <- data_FD$interest_over_time
  
  y <- rbind(y, data_FD[,c(1,2,6)])
  
}
category ="FD"
suffix = "m"
 path <- path_keyword(category, geo, suffix)
 path
write_csv(y, path)

FD_data <- y
#2) 
FD_data <- read_csv("/Users/annevalder/Desktop/UNI /WU WIEN/SoSe_21/MA/data/raw/at/FD_m.csv")

cat_FD2 <- categories  %>% filter(id %in% c(71,277,404, 406, 405, 906, 122, 907, 908, 909, 910, 825, 911,912, 913,914,915, 297, 121,560, 916, 276, 917, 918, 816))

colnames(cat_FD2)[colnames(cat_FD2) %in% c("name", "id")] <- c("name", "category")

FD_data$category <- as.integer(FD_data$category)
cat_FD2$category <- as.integer(cat_FD2$category)
class(FD_data$category)
class(cat_FD2$category)

FD_data <- left_join(FD_data, cat_FD2, by="category")
FD_data <- FD_data[,-3]

##########

colnames(FD_data)[colnames(FD_data) %in% c("date", "hits", "name")] <- c("time", "value", "category")
col_order <- c("category", "time", "value"
               )
FD_data <- FD_data[, col_order]

#FD_data <- F_D_data %>% filter(category == "Arts Education")
# check i fi have duplicated series!!
duplicated(FD_data)
FD_data <- unique(FD_data)


smry <- ts_summary(FD_data)
smry
stopifnot(nrow(dplyr::distinct(smry, start, end)) == 1)

pca_ts <- ts_prcomp(FD_data)

seas_adj <- filter(pca_ts, id == "PC1")%>%
  mutate(value = -value) %>%
  select(-id) %>%
  ts_scale()

#pca <- prcomp(ts_ts(F_D_data), scale = TRUE)

x <- read_csv(/Users/annevalder/Desktop/UNI /WU WIEN/SoSe_21/MA/data/raw/at/"F&D_PC1.csv")

x<- write_keyword(seas_adj, "F&D", "at", "PC1")
ts_plot(x) # PC1 Education!
plot(x)

x <- x[25:211,]

#### bruachc als vergleich %GDP eh das was ioch hab aber hgeht da nur bis 2019 nihct corona schaut deshlanb anders ajs!

#  x in quarterly

x_mntly <- arrange(x, time)

x_mntly$qdate <- as.yearqtr(x_mntly$time)

x_qtrly <- x_mntly %>% group_by(qdate) %>%
  summarise_all(mean)

x_qtrly <- x_qtrly[1:61,]

####graph

x_qtrly_PRE <- x_qtrly[1:56,]
GDP_qtrly_PRE <- GDP_qtrly[1:56,]   ### need GDP quarterl aus MA_MODELS RMD
  
  ##### doch 2004 ??????
#
ggplot(GDP_qtrly_PRE, aes(x=Date)) +
  geom_line(aes(y = Value), color = "steelblue") +
  geom_line(aes(y = x_qtrly_PRE$value), color = "red") +
    theme_light() +
    labs( x = "Years", y = "GDP growth (%) and Google PC1")+
    theme(plot.title = element_text(hjust = 0.5, face ="bold")) +
  scale_x_date(limit=c(as.Date("2006-01-01"),as.Date("2019-01-31")),date_labels="%b %y",date_breaks  ="24 month")

```
##### PPLOT PC1 F&D noch im vgl zum CCI ! und correlation?



```{r}


CCI_qtrly_fin_PRE <- CCI_qtrly_fin[1:56,] 



ggplot(CCI_qtrly_fin, aes(x=Date)) +
  geom_line(aes(y = Value), color = "steelblue") +
    geom_line(aes(y = x_qtrly$value), color = "red") +
  theme_light() +
    labs( x = "Years", y = "Consumer Confidence and Google PC1")+
  theme(plot.title = element_text(hjust = 0.5, face ="bold")) +
  scale_x_date(limit=c(as.Date("2006-01-01"),as.Date("2021-01-31")),date_labels="%b %y",date_breaks  ="24 month")

plot.ts(x_qtrly$value)

cor(CCI_qtrly_fin$Value,x_qtrly$value)

```





Pivot wider 
```{r}

#####  ruach ich nich t für PCA!

F_D_data_wide <-F_D_data %>% 
    pivot_wider(
      
      # from which variable should the new column names be taken from
      names_from = category, 
      
      # from which variable should the values be taken from
      values_from = value)

```